Add notes for Surah Asar and Surah Humaza
miankhalid/dora-e-quran pull request #20
Opened 2019-10-14 06:30 UTC by mushtaqak

This PR adds notes for 103: Surah Asar and 104: Surah Humaza

2019-10-26 09:45 UTC, miankhalid requested changes
Some nits and a general suggestion to either use full stops everywhere or not use them at all in case of bullet points.

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/103_Surah_Asar.md
> +### Zamane ki qasam Insan bare khasare m h
mein hai

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/103_Surah_Asar.md
> +### Sawai wo log jo in 4 kaam poore karta ho
Siwaye wo log jo in 4 kaamon ko poora kartay hon

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/103_Surah_Asar.md
> +5. Allah par uske rasool malaik aakhrat par imaan la kar phr Allah k batae huey un baato par amal kre. na sirf khud balqai wo haq/islam ki baat dusro tak pohchaye ... jb yeh kam kre ga to museebatein
Nits:
- 4 kaam alag or final description alag alag honay chahiyein.
- Allah par, uskay rasool par, malaika par aur akhirat par imaan la kar phir Allah k batai hoi baato par amal kre. Na sirf khud balqai wo haq/islam ki baat dusro tak pohchaye ... jb yeh kam kre ga to museebatein aaye gi. Tab ja k sabar se kaam le.

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/103_Surah_Asar.md
> +4. Sabar ki talqain.
1 - Jo imaan laaye.
2 - Naik amal karay.
3 - Haq ke naseehat karay.
4 - Or sabar ke talqeen karay.

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/104_Surah_Humaza.md
> + Jo surah Asar k rasty par ni chalty yeh surah unka qurdaar dikha rhi h
kirdaar

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/104_Surah_Humaza.md
> +2. Tanabazi karta ho
Taanay baazi

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/104_Surah_Humaza.md
> +4. smjhta h maal usko hamesha zinda rakhy gq
`Smjhta` h k maal usko hamesha zinda rakhay `ga`

2019-10-26 09:45 UTC, miankhalid commented on notes/roman-urdu/104_Surah_Humaza.md
> +1. Us skhs ko Hutama m daala jaye ga jo.
Us shakhs ko Hutama m daala jaye ga

2019-11-25 12:05 UTC, mushtaqak commented
@miankhalid addressed your feedback. Kindly review again :)

2019-12-30 09:55 UTC, miankhalid approved these changes
Jazak Allah

2019-12-30 09:55 UTC, merged